package com.catignascabela.dodapplication;

import android.content.Intent;
import android.os.Bundle;
import android.text.TextUtils;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.RadioButton;
import android.widget.RadioGroup;
import android.widget.TextView;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;

import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

import java.util.HashMap;

public class TeacherRegistrationActivity extends AppCompatActivity {

    private EditText username, password, fullName;
    private RadioGroup departmentRadioGroup;
    private Button registerButton;
    private TextView loginLink;
    private FirebaseAuth auth;
    private FirebaseDatabase database;
    private DatabaseReference pendingTeachersRef;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_teacher_registration);

        // Initialize Firebase Auth and Realtime Database
        auth = FirebaseAuth.getInstance();
        database = FirebaseDatabase.getInstance();
        pendingTeachersRef = database.getReference("pending_teachers");  // Reference to pending_teachers node

        // Initialize UI components
        username = findViewById(R.id.register_username);
        password = findViewById(R.id.register_password);
        fullName = findViewById(R.id.register_full_name);
        departmentRadioGroup = findViewById(R.id.radio_group_department); // RadioGroup for department
        registerButton = findViewById(R.id.register_button);
        loginLink = findViewById(R.id.registered_text); // Corrected ID for login link

        // Set click listener for register button
        registerButton.setOnClickListener(v -> registerTeacher());

        // Set click listener for login link
        loginLink.setOnClickListener(v -> {
            Intent intent = new Intent(TeacherRegistrationActivity.this, LoginActivity.class);
            startActivity(intent);
            finish();
        });
    }

    private void registerTeacher() {
        String usernameValue = username.getText().toString().trim();
        String passwordValue = password.getText().toString().trim();
        String fullNameValue = fullName.getText().toString().trim();

        // Get selected department
        int selectedDepartmentId = departmentRadioGroup.getCheckedRadioButtonId();
        RadioButton selectedDepartment = findViewById(selectedDepartmentId);
        String departmentValue = selectedDepartment != null ? selectedDepartment.getText().toString() : "";

        // Validate input fields
        if (TextUtils.isEmpty(usernameValue) || TextUtils.isEmpty(passwordValue) ||
                TextUtils.isEmpty(fullNameValue) || TextUtils.isEmpty(departmentValue)) {

            Toast.makeText(this, "Please fill in all required fields", Toast.LENGTH_SHORT).show();
            return;
        }

        // Generate email for the teacher (autogenerated)
        String teacherEmail = usernameValue + "@luteacher.com";

        // Register teacher in Firebase Authentication
        auth.createUserWithEmailAndPassword(teacherEmail, passwordValue)
                .addOnCompleteListener(task -> {
                    if (task.isSuccessful()) {
                        FirebaseUser user = auth.getCurrentUser();
                        if (user != null) {
                            saveTeacherData(user.getUid(), usernameValue, fullNameValue, teacherEmail, departmentValue);
                        }
                    } else {
                        Toast.makeText(TeacherRegistrationActivity.this,
                                "Registration failed: " + task.getException().getMessage(),
                                Toast.LENGTH_SHORT).show();
                    }
                });
    }

    private void saveTeacherData(String uid, String username, String fullName, String email, String department) {
        // Create a HashMap to store teacher data
        HashMap<String, Object> teacherData = new HashMap<>();
        teacherData.put("uid", uid); // Add this line
        teacherData.put("username", username);
        teacherData.put("fullName", fullName);
        teacherData.put("email", email);
        teacherData.put("department", department);
        teacherData.put("isApproved", false);

        // Save teacher data to the Realtime Database under pending_teachers
        pendingTeachersRef.child(uid).setValue(teacherData)
                .addOnSuccessListener(aVoid -> {
                    Toast.makeText(TeacherRegistrationActivity.this, "Registration successful! Awaiting approval.", Toast.LENGTH_SHORT).show();
                    startActivity(new Intent(TeacherRegistrationActivity.this, LoginActivity.class));
                    finish();
                })
                .addOnFailureListener(e ->
                        Toast.makeText(TeacherRegistrationActivity.this,
                                "Error saving data: " + e.getMessage(),
                                Toast.LENGTH_SHORT).show());
    }

}
